#!/bin/bash
set -eu
set -o pipefail
set -x

which ocrd >/dev/null 2>/dev/null || { echo "ocrd not in \$PATH. Panicking"; exit 1; }

SHAREDIR="$(cd "$(dirname "$0")" >/dev/null && pwd)"
SCRIPT_NAME="${0##*/}"

MIMETYPE_PAGE=$(ocrd bashlib constants MIMETYPE_PAGE)

# FIXME: add a bashlib wrapper for logging to use here
function log {
    echo >&2 "$(date +%T.%3N) $LEVEL $SCRIPT_NAME - $*"
}
function critical { LEVEL=CRITICAL log "$*"; }
function error { LEVEL=ERROR log "$*"; }
function warning { LEVEL=WARNING log "$*"; }
function info { LEVEL=INFO log "$*"; }
function debug { LEVEL=DEBUG log "$*"; }

main () {
    # Load ocrd bashlib functions
    # shellcheck source=../core/ocrd/bashlib/lib.bash
    source $(ocrd bashlib filename)

    # Describe calling script to lib.bash
    ocrd__wrap "$SHAREDIR/ocrd-tool.json" "$SCRIPT_NAME" "$@"

    cd "${ocrd__argv[working_dir]}"
    IFS=',' read -ra in_grps <<< "${ocrd__argv[input_file_grp]}"
    echo $in_grps
    in_file_grp="${in_grps[0]}"
	img_file_grp="${in_grps[1]}"
    out_file_grp=${ocrd__argv[output_file_grp]}
    mkdir -p $out_file_grp

    # read params
    local from_to script_args output_extension
    text_source=(${params['text-source']:-""})
    font=(${params['font']:-""})
    outlines=(${params['outlines']:-""})
    neg2zero=(${params['negative2zero']})

    # Parameters
    if [ ${#font} -gt "0" ]; then
        echo "VAR is not empty"
        font="-font $font"
    fi
    if [ ${#text_source} -gt "0" ]; then 
        text_source="-text-source $text_source"
    fi
    if [ ${#outlines} -gt "0" ]; then 
        outlines="-outlines $outlines"
    fi

    script_args=(${params['script-args']})
    output_extension=${params['ext']}


    # Download the files and do the conversion
    local IFS=$'\n'
    files=($(ocrd workspace find \
        ${page_id:+-g} ${page_id:-} \
        -G $in_file_grp \
        -k local_filename \
        -k ID \
        -k pageId \
        --download))
    local IFS=$' \t\n'
    local n=0 zeros=0000
    for csv in "${files[@]}"; do
        let n+=1
        # Parse comma separated fields
        local IFS=$'\t'
        local fields=($csv)
        local IFS=$' \t\n'

        local in_file="${fields[0]}"
        local in_id="${fields[1]}"
        local pageid="${fields[2]:-}"
		
		if ! test -f "$in_file"; then
           error "input file \"$in_file\" ID=${in_id} (pageId=${pageid}) is not on disk"
           continue
        fi
        
        # Rework coords in PAGE
        if [ $neg2zero = True ]; then
            python3 "$SHAREDIR/ptp/negative2zero.py" "$in_file" "$in_file.rework"
		    in_file="$in_file.rework"
        fi
		
        img_file=($(ocrd workspace find \
        -g $pageid \
        -G $img_file_grp \
        -k local_filename \
        --download))

        if ! test -f "$img_file"; then
           error "no image file in  \"$img_file_grp\""
           continue
        fi

        # Output filename
        local out_id="${in_id//$in_file_grp/$out_file_grp}"
        if [ "x$out_id" = "x$in_id" ]; then
            out_id=${out_file_grp}_${zeros:0:$((4-${#n}))}$n
        fi
        local out_file="$out_file_grp/${out_id}$output_extension"

	
        java -jar "$SHAREDIR/ptp/PageToPdf.jar" $font $text_source $outlines -xml "$in_file" -image "$img_file" -pdf "$out_file"

        if [ $repair = True ]; then
            rm $in_file
        fi

    done
}


main "$@"
